name: 'Setup and Build Docker'
description: 'Checkout code, setup Docker Buildx, and build Docker images.'
inputs:
  ref:
    description: 'The GitHub ref that triggered the workflow.'
    required: true
runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
