name: 'Setup and Build Docker'
description: 'Checkout code, setup Docker Buildx, and build Docker images.'
runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker images
      uses: docker/bake-action@v4
      with:
        pull: true
        load: true
        files: |
          compose.yaml
          compose.override.yaml
        set: |
          *.cache-from=type=gha,scope=${{github.ref}}
          *.cache-from=type=gha,scope=refs/heads/main
          *.cache-to=type=gha,scope=${{github.ref}},mode=max
          
    - name: Start services
      run: docker compose up --wait --no-build
