name: CI
run-name: Run CI workflow for ${{ github.ref_name }} branch
on: [push]
jobs:
  reachability:
    name: Reachability
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup and Build Docker
        uses: ./.github/actions/setup-and-build-docker

      - name: Check HTTP reachability
        run: curl -v --fail-with-body http://localhost

  code-quality:
    name: Code Quality
    # needs: reachability
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup and Build Docker
        uses: ./.github/actions/setup-and-build-docker

      - name: Copy PHPStan config file
        run: docker compose exec -T php cp phpstan.dist.neon phpstan.neon
      
      - name: Run PHPStan
        run: docker compose exec -T php vendor/bin/phpstan analyse -c ./phpstan.neon

  tests:
    name: Unit Tests
    # needs: reachability
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup and Build Docker
        uses: ./.github/actions/setup-and-build-docker
      
      - name: Create test database
        run: docker compose exec -T php bin/console -e test doctrine:database:create
      
      - name: Run migrations
        run: docker compose exec -T php bin/console -e test doctrine:migrations:migrate --no-interaction
      
      - name: Copy PHPUnit config file
        run: docker compose exec -T php cp phpunit.xml.dist phpunit.xml
      
      - name: Unit Tests
        run: docker compose exec -T php bin/phpunit -c ./phpunit.xml ./tests/Unit
      
      - name: Integration Tests
        run: docker compose exec -T php bin/phpunit -c ./phpunit.xml ./tests/Integration

      - name: Functional Tests
        run: docker compose exec -T php bin/phpunit -c ./phpunit.xml ./tests/Functional
