name: CI
run-name: Run CI workflow for ${{ github.ref_name }} branch
on: [push]
jobs:
  reachability:
    name: Reachability
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup and Build Docker
        uses: ./.github/actions/setup-and-build-docker

      - name: Check HTTP reachability
        run: curl -v --fail-with-body http://localhost

  tests:
    name: Unit Tests
    needs: reachability
    runs-on: ubuntu-latest
    steps:
      - name: Unit Tests
        run: XDEBUG_MODE=off php bin/console ./tests/Unit
